# .github/workflows/retrain.yml
name: Retrain Model

 on:
 # schedule:
 #   - cron: '0 0 * * *'  # daily at midnight UTC
 # workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Forecast Pipeline
        run: python forecast_pipeline.py

      - name: Commit Trained Model
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add model/
          git commit -m "Daily model retraining"
          git push || echo "No changes to commit."
